name: Python application

on:
  push:
    branches:
    - main
  schedule:
  - cron: "00 20 * * 1-5"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install gspread oauth2client 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Show
      run: |
        pwd
    - name: Lists
      run: |
        ls
    - name: Run scriptGoogle.py
      run: |
        chmod +x scriptGoogle.py
    - name: Debug Output
      run: |
        python scriptGoogle.py
    
